### 📋 Obtener todas las membresías
GET http://localhost:5500/api/membresias
Content-Type: application/json


### ➕ Crear una nueva membresía
POST http://localhost:5500/api/membresias
Content-Type: application/json

{
  "nro": "001",
  "nombre": "Premium",
  "descripcion": "Acceso full al gym",
  "precio": 2500
}


### 🔍 Buscar una membresía por ID
GET http://localhost:5500/api/membresias/ID_AQUI
Content-Type: application/json


### ✏️ Actualizar una membresía
PUT http://localhost:5500/api/membresias/ID_AQUI
Content-Type: application/json

{
  "precio": 3000
}


### ❌ Eliminar una membresía
DELETE http://localhost:5500/api/membresias/ID_AQUI
Content-Type: application/json
