### obtener todos los Usuarios
GET http://localhost:3000/api/Usuarios


### obtener un Usuario
GET http://localhost:3000/api/Usuarios/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo Usuario
POST http://localhost:3000/api/Usuarios
Content-Type: application/json

{
  "name": "Atila",
  "UsuarioClass": "warrior",
  "items": ["bow","arrow"],
  "attack": 10,
  "mana": 10,
  "hp": 10,
  "level": 1
}

### modificar un Usuario (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/Usuarios/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name": "Anakin Skywalker",
  "UsuarioClass": "Fallen Jedi",
  "items": ["Lightsaber", "Death Star"],
  "attack": 110,
  "mana": 500,
  "hp": 100,
  "level": 11    
}

### modificar un Usuario (PATCH - recurso parcial)
PATCH http://localhost:3000/api/Usuarios/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
  "name": "Anakin Skywalker",
  "UsuarioClass": "Fallen Jedi",
  "items": ["Lightsaber", "X-Wing"],
  "level": 12    
}

### borrar un Usuario
DELETE http://localhost:3000/api/Usuarios/a02b91bc-3769-4221-beb1-d7a3aeba7dad