### obtener todos los Usuarios
GET http://localhost:5500/api/Usuarios




### crear un nuevo Usuario
# @name crearJuanPerez
POST http://localhost:5500/api/Usuarios
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "tel": 41231234,
  "mail": "JuanPerez@gmail.com"
}

### ID - Debe ejecutarse después de crearJuanPerez
@id = {{crearJuanPerez.response.body.data.id}}

### obtener un Usuario
GET http://localhost:5500/api/Usuarios/{{id}}

### modificar un Usuario (PUT - recurso completo e idempotente)
PUT http://localhost:5500/api/Usuarios/{{id}}
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Perez",
  "tel": 41234321,
  "mail": "jp@gmail.com"  
}

### crear un nuevo Usuario
POST http://localhost:5500/api/Usuarios
Content-Type: application/json

{
  "nombre": "Facundo",
  "apellido": "juarez",
  "tel": 3232323,
  "mail": "facundo@gmail.com"   
}

### crear un nuevo Usuario
# @name crearUsuarioParaBorrar
POST http://localhost:5500/api/Usuarios
Content-Type: application/json

{
  "nombre": "Pedro",
  "apellido": "Sanchez",
  "tel": 1234567,
  "mail": "PedroSanchezo@gmail.com"   
}

### modificar un Usuario (PATCH - recurso parcial)
@idParaBorrar = {{crearUsuarioParaBorrar.response.body.data.id}}
PATCH http://localhost:5500/api/Usuarios/{{idParaBorrar}}
Content-Type: application/json

{
  "tel": 341897666,
  "mail" : "ps@gmail.com"   
}

### borrar un Usuario
DELETE http://localhost:5500/api/Usuarios/{{idParaBorrar}}

