### GET ALL
GET http://localhost:5500/api/actividad

### POST
# @name createActividad
POST http://localhost:5500/api/actividad
Content-Type: application/json

{
    "nombre": "Yoga",
    "descripcion": "Clase de yoga para todos los niveles",
    "cupo": 20
}

### ID
@id = {{createActividad.response.body.data.id}}

### GET ONE
GET http://localhost:5500/api/actividad/{{id}}


### PUT
PUT http://localhost:5500/api/actividad/{{id}}
Content-Type: application/json

{
    "nombre": "Yoga Avanzado",
    "descripcion": "Clase de yoga avanzada",
    "cupo": 15
}

### POST2
POST http://localhost:5500/api/actividad
Content-Type: application/json

{
    "nombre": "Spinning",
    "descripcion": "Clase de spinning de alta intensidad",
    "cupo": 25
}

### POST3
POST http://localhost:5500/api/actividad
Content-Type: application/json

{
    "nombre": "Pilates",
    "descripcion": "Clase de pilates para fortalecer el core",
    "cupo": 18
}



### añadir una actividad a un Entrenador
# Cambia el valor de "actividadId" por el id real de una actividad existente
PATCH http://localhost:5500/api/actividad/{{id}} 
Content-Type: application/json

{
  "entrenadores": ["ID_DE_ENTRENADOR_ACA"]
}




### POST ACTIVIDAD TO DELETE
# @name createActividadToDelete
POST http://localhost:5500/api/actividad
Content-Type: application/json

{
    "nombre": "Zumba",
    "descripcion": "Clase de zumba para quemar calorías",
    "cupo": 30
}

### DELETE
@idToDelete = {{createActividadToDelete.response.body.data.id}}
DELETE http://localhost:5500/api/actividad/{{idToDelete}}